# Generated by Django 3.2.9 on 2021-12-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211219_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
